language: node_js
node_js:
  - "0.12"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm install -g grunt-cli

before_script:
  - npm install -g bower
  - bower install

#travis build  speed up
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
